"use client";
import { useState } from "react";
import { Button, Fact, Facts, Notice, PageHeader, Panel, Pill, Sheet, Skeleton } from "web-shared";
import { fetchCampaign, fetchCampaigns, fetchPromotion, fetchPromotions } from "@/lib/api";
import { useResource } from "@/lib/use-resource";
import { campaignRoas, localDateTime, money } from "@/lib/retail-format";
import PageControls from "@/components/PageControls";

function CampaignDetail({ id, onClose, onAsk }: { id: string; onClose: () => void; onAsk: (text: string) => void }) {
  const { data, error } = useResource(() => fetchCampaign(id), [id]);
  const campaign = data?.campaign;
  return <Sheet title="营销计划与观察" detail={id} onClose={onClose} closeLabel="关闭营销计划">{error ? <Notice>{error}</Notice> : !campaign ? <Skeleton className="h-60" /> : <><h2 className="text-xl font-semibold">{campaign.name}</h2><Pill>{campaign.state}</Pill><Facts><Fact label="计划预算" value={money(campaign.budgetMinor == null ? null : campaign.budgetMinor / 100, campaign.currency)} /><Fact label="渠道" value={campaign.channel ?? "未设置"} /><Fact label="观察支出" value={money(campaign.spendMinor == null ? null : campaign.spendMinor / 100, campaign.currency)} /><Fact label="归因收入" value={money(campaign.revenueMinor == null ? null : campaign.revenueMinor / 100, campaign.currency)} /><Fact label="同期 ROAS" value={campaignRoas(campaign)} /></Facts><dl className="space-y-3 text-sm">{[["目标", campaign.objective], ["受众", campaign.audience], ["营销文案", campaign.copyText]].map(([label, value]) => <div key={label}><dt className="font-semibold">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-(--ink-soft)">{value ?? "未设置"}</dd></div>)}</dl><p className="text-sm">计划期间：{localDateTime(campaign.startsAt)} 至 {localDateTime(campaign.endsAt)} · Asia/Shanghai</p><section className="rounded-lg bg-(--ground) p-3 text-xs text-(--ink-soft)"><p>观察期间：{localDateTime(campaign.observationStart)} 至 {localDateTime(campaign.observationEnd)}（结束不含）</p><p className="mt-2 break-all">来源：{campaign.observationSourceKind ?? "暂无观察"}{campaign.observationSourceRef ? ` · ${campaign.observationSourceRef}` : ""}{campaign.fixtureVersion ? ` · 数据版本 ${campaign.fixtureVersion}` : ""}</p><p className="mt-2">预算是本地计划；支出与归因收入是单独的历史观察。缺失值不是零，本站不会执行外部广告投放。</p></section><Button variant="primary" icon="spark" onClick={() => { onAsk(`分析营销计划 ${id} 的同期支出、归因收入与ROAS，并为预算、受众或文案提出有依据的调整草案，等我批准。`); onClose(); }}>分析并准备调整</Button></>}</Sheet>;
}
function PromotionDetail({ id, onClose, onAsk }: { id: string; onClose: () => void; onAsk: (text: string) => void }) {
  const { data, error } = useResource(() => fetchPromotion(id), [id]);
  const promotion = data?.promotion;
  return <Sheet title="已批准促销" detail={id} onClose={onClose} closeLabel="关闭促销详情">{error ? <Notice>{error}</Notice> : !promotion ? <Skeleton className="h-60" /> : <><h2 className="text-xl font-semibold">{promotion.name}</h2><p className="text-sm">优惠 {(promotion.discountBasisPoints / 100).toFixed(2)}% · 批准于 {localDateTime(promotion.appliedAt)}</p><Notice>批准时已实际改价。下面的经营窗口结束后，售价不会自动恢复；当前售价单独列示。</Notice><p className="text-sm">经营窗口：{localDateTime(promotion.startsAt)} 至 {localDateTime(promotion.endsAt)}（结束不含） · Asia/Shanghai</p><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["SKU", "批准前", "批准促销价", "当前价"].map(label => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{promotion.targets.map(target => <tr key={target.productId} className="border-t border-(--line)"><td className="p-2"><span className="break-all">{target.productId}</span>{target.overridden && <Pill tone="warn">价格或币种已变更</Pill>}</td><td className="p-2 whitespace-nowrap">{money(target.approvedBasePriceMinor / 100, promotion.currency)}</td><td className="p-2 whitespace-nowrap">{money(target.promotionPriceMinor / 100, promotion.currency)}</td><td className="p-2 whitespace-nowrap">{money(target.currentPriceMinor / 100, target.currentCurrency)}</td></tr>)}</tbody></table></div><p className="break-all text-xs text-(--ink-soft)">来源草案 {promotion.sourceChangeId}。当前版本变化不一定代表价格发生变化。</p><Button variant="primary" icon="spark" onClick={() => { onAsk(`检查已批准促销 ${id} 的当前商品价格与经营表现，再建议下一步动作。不要假设经营窗口结束后价格会自动恢复。`); onClose(); }}>分析此促销</Button></>}</Sheet>;
}
export default function MarketingView({ refreshKey, onAskAssistant }: { refreshKey: number; onAskAssistant: (text: string) => void }) {
  const [tab, setTab] = useState<"campaigns" | "promotions">("campaigns");
  const [campaignOffset, setCampaignOffset] = useState(0);
  const [promotionOffset, setPromotionOffset] = useState(0);
  const [selected, setSelected] = useState<{ kind: "campaigns" | "promotions"; id: string } | null>(null);
  const campaigns = useResource(() => fetchCampaigns(campaignOffset), [campaignOffset, refreshKey]);
  const promotions = useResource(() => fetchPromotions(promotionOffset), [promotionOffset, refreshKey]);
  return <div className="ac-reveal flex flex-col gap-4"><PageHeader title="营销与促销" subtitle="查看本地营销计划和已批准促销；新增与修改通过草案审批。"><Button variant="secondary" icon="spark" onClick={() => onAskAssistant(tab === "campaigns" ? "根据当前报告期间的经营事实，准备一份有明确目标、受众和预算的本地营销计划，等我批准。" : "读取当前商品、库存和成本，为适合的商品准备促销草案。按今天真实上海日期指定允许批准窗口，并说明实际改价及到期不自动恢复，等我批准。")}>{tab === "campaigns" ? "准备营销计划" : "准备促销方案"}</Button></PageHeader><div className="flex gap-2"><Button variant={tab === "campaigns" ? "primary" : "secondary"} onClick={() => setTab("campaigns")}>营销计划</Button><Button variant={tab === "promotions" ? "primary" : "secondary"} onClick={() => setTab("promotions")}>已批准促销</Button></div>
    {tab === "campaigns" ? campaigns.error ? <Notice>{campaigns.error}</Notice> : !campaigns.data ? <Skeleton className="h-64" /> : <><Notice>计划在本站保存，不会投放到外部广告平台。历史支出与归因收入保留原观察期间。</Notice><div className="grid items-start gap-4 xl:grid-cols-2">{campaigns.data.campaigns.map(campaign => <Panel key={campaign.campaignId} title={campaign.name} subtitle={`${campaign.campaignId} · ${campaign.state}`}><div className="space-y-3 p-4"><p className="text-sm text-(--ink-soft)">{campaign.objective ?? "未设置目标"}</p><Facts><Fact label="预算" value={money(campaign.budgetMinor == null ? null : campaign.budgetMinor / 100, campaign.currency)} /><Fact label="同期 ROAS" value={campaignRoas(campaign)} /></Facts><Button variant="secondary" size="sm" onClick={() => setSelected({ kind: "campaigns", id: campaign.campaignId })}>查看计划与来源</Button></div></Panel>)}</div>{!campaigns.data.campaigns.length && <Notice>此页没有营销计划。</Notice>}<PageControls offset={campaignOffset} nextOffset={campaigns.data.next_offset} pageSize={24} onPage={setCampaignOffset} /></> : promotions.error ? <Notice>{promotions.error}</Notice> : !promotions.data ? <Skeleton className="h-64" /> : <><Notice>仅列出已经批准执行的促销。待批准方案请到“草案与审批历史”核对；促销到期不自动恢复价格。</Notice><div className="grid items-start gap-4 xl:grid-cols-2">{promotions.data.promotions.map(promotion => <Panel key={promotion.promotionId} title={promotion.name} subtitle={promotion.promotionId}><div className="space-y-3 p-4"><p className="text-sm">优惠 {(promotion.discountBasisPoints / 100).toFixed(2)}% · {promotion.targets.length} 个 SKU</p><p className="text-xs text-(--ink-soft)">{localDateTime(promotion.startsAt)} 至 {localDateTime(promotion.endsAt)} · Asia/Shanghai</p><Button variant="secondary" size="sm" onClick={() => setSelected({ kind: "promotions", id: promotion.promotionId })}>核对促销与当前价格</Button></div></Panel>)}</div>{!promotions.data.promotions.length && <Notice>此页没有已批准促销。</Notice>}<PageControls offset={promotionOffset} nextOffset={promotions.data.next_offset} pageSize={24} onPage={setPromotionOffset} /></>}
    {selected?.kind === "campaigns" && <CampaignDetail key={selected.id} id={selected.id} onClose={() => setSelected(null)} onAsk={onAskAssistant} />}{selected?.kind === "promotions" && <PromotionDetail key={selected.id} id={selected.id} onClose={() => setSelected(null)} onAsk={onAskAssistant} />}
  </div>;
}
