// Copyright 2026 Anthropic PBC
// SPDX-License-Identifier: Apache-2.0
"use client";
import { type FormEvent,useCallback,useEffect,useRef,useState } from "react";
import { Button,Chat,Notice,StorePage,StoreShell,type StoreView,useAgentTurn } from "web-shared";
import { buyerApi,UNREACHABLE } from "@/lib/buyer-api";
import { minorMoney } from "@/lib/buyer-checkout";
import type { ActionRecord,BuyerCommand,BuyerProfile,BuyerSession,CartResponse,CheckoutCommand,CheckoutFacts,JavaCart,OrderFacts,Product } from "@/lib/buyer-types";
import type { LoginResult,SavedSession } from "@/lib/api";
import GenerativeBlock from "@/components/buyer/generative";
import Catalog from "@/components/buyer/Catalog";
import CartPanel from "@/components/buyer/CartPanel";
import Checkout from "@/components/buyer/Checkout";
import Orders from "@/components/buyer/Orders";
import Profile from "@/components/buyer/Profile";
import Commands from "@/components/buyer/Commands";

type View="assistant"|"catalog"|"orders"|"checkout"|"profile";
function Login({onLogin}:{onLogin:(id:string,password:string)=>Promise<void>}) {
 const[id,setId]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError(null);try{await onLogin(id,password);}catch(error){setError(error instanceof Error?error.message:UNREACHABLE);}finally{setPassword("");setBusy(false);}}
 return <main className="grid min-h-dvh place-items-center p-5"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-2xl border border-(--line) bg-(--card) p-7 shadow-(--shadow)"><div><a href="/" className="text-xs font-semibold underline">商家经营工作台 ↗</a><h1 className="mt-3 text-2xl font-semibold">ShopMate 购物助手</h1><p className="mt-2 text-sm text-(--ink-soft)">推荐、比较、规划与购物；订单、付款和退款由你确认。</p></div><label className="block text-sm">买家账号<input autoComplete="username" required value={id} onChange={e=>setId(e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2"/></label><label className="block text-sm">密码<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2"/></label>{error&&<p role="alert" className="text-(--danger)">{error}</p>}<Button type="submit" disabled={busy}>{busy?"登录中…":"登录买家工作台"}</Button><p className="text-xs text-(--ink-soft)">登录凭证只存在页面内存。刷新后重新登录，可以恢复会话与已保存的业务结果。</p></form></main>;
}
function BuyerWorkbench({selected,subject,sessions,sessionBusy,onSelect,onCreate,onReload,onLogout,onBusy}:{selected:BuyerSession;subject:string;sessions:SavedSession[];sessionBusy:boolean;onSelect:(id:string)=>void;onCreate:()=>void;onReload:()=>void;onLogout:()=>void;onBusy:(value:boolean)=>void}) {
 const[view,setView]=useState<View>("assistant");const[panelOpen,setPanelOpen]=useState(false);const[quote,setQuote]=useState<JavaCart|null>(null);const[commands,setCommands]=useState<BuyerCommand[]>(selected.commands);const[checkouts,setCheckouts]=useState<CheckoutFacts[]>(selected.checkouts);const[actions,setActions]=useState<ActionRecord[]>(selected.actions);const[orders,setOrders]=useState<OrderFacts[]|null>(null);const[profile,setProfile]=useState<BuyerProfile|null>(null);const[error,setError]=useState<string|null>(null);const[readError,setReadError]=useState<string|null>(null);const[actionBusy,setActionBusy]=useState(false);const[reading,setReading]=useState(false);const[revision,setRevision]=useState(0);const[stopped,setStopped]=useState(false);const[localVersion,setLocalVersion]=useState(0);const lock=useRef(false);const alive=useRef(true);
 const refresh=useCallback(async()=>{if(!alive.current)return;setReading(true);try{
  const [cart,cmds,checks,acts,owned,prefs]=await Promise.all([buyerApi.get<CartResponse>("/cart"),buyerApi.get<{commands:BuyerCommand[]}>("/commands"),buyerApi.get<{checkouts:CheckoutFacts[]}>("/checkouts"),buyerApi.get<{actions:ActionRecord[]}>("/actions"),buyerApi.get<{orders:OrderFacts[]}>("/orders",{limit:"20"}),buyerApi.get<{profile:BuyerProfile}>("/profile")]);
  if(!alive.current)return;setQuote(cart.quote);setCommands(cmds.commands);setCheckouts(checks.checkouts);setActions(acts.actions);setOrders(owned.orders);setProfile(prefs.profile);for(const command of cmds.commands)if(command.state!=="unknown")buyerApi.acknowledge(command.request_key);setLocalVersion(n=>n+1);setReadError(null);setRevision(n=>n+1);
 }catch(error){if(alive.current)setReadError(error instanceof Error?error.message:UNREACHABLE);}finally{if(alive.current)setReading(false);}},[]);
 const running=selected.status==="running"||selected.run_status==="running";
 const turn=useAgentTurn(buyerApi,{sessionId:running?null:selected.session_id,initialItems:selected.items,unreachable:UNREACHABLE,onTurnEnd:()=>{void refresh();}});
 const busy=turn.busy||running||actionBusy||sessionBusy;const unresolved=commands.some(command=>command.state==="unknown"&&(command.kind==="cart"||command.kind==="checkout"))||buyerApi.pendingWrites().some(item=>item.path.startsWith("/cart")||item.path.startsWith("/checkouts"));
 const transactionDisabled=busy||reading||readError!==null||unresolved;
 useEffect(()=>{alive.current=true;void refresh();return()=>{alive.current=false;buyerApi.stopChat();};},[refresh]);
 useEffect(()=>{buyerApi.onReadError=setError;return()=>{buyerApi.onReadError=null;};},[]);
 useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
 useEffect(()=>{buyerApi.page={page_type:view==="orders"?"orders":view==="catalog"?"search":view==="checkout"?"cart":view==="assistant"?"home":"other"};},[view]);
 async function perform(fn:()=>Promise<unknown>){if(lock.current||turn.busy||running||sessionBusy)return;lock.current=true;setActionBusy(true);setError(null);try{await fn();}catch(error){if(alive.current)setError(error instanceof Error?error.message:UNREACHABLE);}finally{await refresh();lock.current=false;if(alive.current){setActionBusy(false);setLocalVersion(n=>n+1);}}}
 const send=async(text:string)=>{if(lock.current||turn.busy||running||sessionBusy)return;setStopped(false);setError(null);await turn.send(text);};
 const chat={...turn,send,ready:turn.ready&&!busy&&!reading};
 async function add(product:Product):Promise<boolean>{if(transactionDisabled||lock.current)return false;let success=false;await perform(async()=>{await buyerApi.write<CartResponse>("/cart/add",{productId:product.product_id,quantity:1});success=true;});return success;}
 function openCheckout(){if(busy)return;setView("checkout");setPanelOpen(false);void refresh();}
 const retry=(command:BuyerCommand)=>void perform(async()=>{const path=command.kind==="cart"?"/commands/retry":command.kind==="checkout"?"/checkouts/retry":"/actions/retry";await buyerApi.post(path,{request_key:command.request_key});buyerApi.acknowledge(command.request_key);});
 const nav:StoreView<View>[]=[{id:"assistant",label:"助手",icon:"spark"},{id:"catalog",label:"商品",icon:"tag"},{id:"orders",label:"订单",icon:"box"},{id:"checkout",label:"结账",icon:"bag"},{id:"profile",label:"资料",icon:"user"}];
 const banner=<><div className="flex flex-wrap items-center gap-2 border-b border-(--line) px-4 py-2"><a href="/" className="text-xs font-semibold underline">商家入口 ↗</a><label htmlFor="buyer-session" className="text-xs">会话</label><select id="buyer-session" className="min-w-0 max-w-xs flex-1 rounded border px-2 py-1 text-xs" disabled={busy} value={selected.session_id} onChange={e=>onSelect(e.target.value)}>{sessions.map(session=><option key={session.session_id} value={session.session_id}>{session.title||"新会话"}</option>)}</select><Button size="sm" variant="secondary" disabled={busy} onClick={onCreate}>新会话</Button><Button size="sm" variant="secondary" disabled={turn.busy||actionBusy||sessionBusy} onClick={onReload}>恢复会话</Button><Button size="sm" variant="secondary" disabled={busy} onClick={onLogout}>退出</Button>{turn.busy&&<Button size="sm" disabled={stopped} onClick={()=>{setStopped(true);buyerApi.stopChat();}}>{stopped?"正在停止…":"停止生成"}</Button>}</div>{(error||readError)&&<p role="alert" className="bg-(--danger-soft) px-4 py-2 text-sm text-(--danger)">{error||readError}{readError&&<button onClick={()=>void refresh()} className="ml-3 underline">重新读取业务状态</button>}</p>}{running&&<p className="bg-(--warn-soft) px-4 py-2 text-sm">服务端仍在运行。稍后点击“恢复会话”读取结果；当前禁止新任务与确认。</p>}{stopped&&!turn.busy&&<p className="bg-(--warn-soft) px-4 py-2 text-sm">连接已停止。点击“恢复会话”核对已保存的状态；已提交业务不会撤销。</p>}<Commands key={localVersion} commands={commands} local={buyerApi.pendingWrites()} session={selected.session_id} disabled={busy||reading} onRetry={retry} onLocalRetry={key=>void perform(()=>buyerApi.retryWrite(key))} onSession={onSelect}/></>;
 return <StoreShell brand={<span className="font-bold">ShopMate</span>} views={nav} view={view} onViewChange={setView} chat={chat} api={buyerApi} assistantName="ShopMate 购物助手" shopper={{name:profile?.display_name??subject,tier:profile?.loyalty_tier??undefined}} bag={{label:"购物车",ariaLabel:`打开购物车，共${quote?.items.reduce((sum,item)=>sum+item.quantity,0)??0}件商品`,count:quote?.items.reduce((sum,item)=>sum+item.quantity,0)??0,noun:"件",figure:quote?minorMoney(quote.subtotalMinor,quote.currency):null}} panel={<CartPanel cart={quote} error={readError} disabled={transactionDisabled} onSet={(productId,quantity,version)=>void perform(()=>buyerApi.write("/cart/set",{productId,quantity,expectedCartVersion:version}))} onRemove={(productId,version)=>void perform(()=>buyerApi.write("/cart/remove",{productId,expectedCartVersion:version}))} onCheckout={openCheckout} onRefresh={()=>void refresh()}/>} panelOpen={panelOpen} onPanelOpenChange={setPanelOpen} placeholder="推荐商品、比较方案、规划购物，或查询本人订单…" banner={banner}>
 <div className={view==="assistant"?"h-full":"hidden"}><Chat chat={chat} wide={new Set(["comparison","plan"])} home={<div className="space-y-4"><h1 className="text-3xl font-semibold">一起把需要的东西选好</h1><p className="text-(--ink-soft)">比较真实商品、选择规格、规划清单；确认前不创建订单或付款。</p><div className="grid gap-2 sm:grid-cols-2">{["为小户型规划一套居家办公用品，预算 800 元，比较不同选择。","推荐一顶适合首次家庭露营的帐篷，预算 250 元。","看看我的订单，区分付款情况和实际配送进度。","记住：我住小户型，没有户外储藏空间，还养了一只金毛犬。"].map(prompt=><button key={prompt} disabled={!chat.ready} className="rounded-xl border border-(--line) bg-(--card) p-4 text-left text-sm disabled:opacity-50" onClick={()=>void send(prompt)}>{prompt}</button>)}</div></div>} renderBlock={segment=><GenerativeBlock block={segment.block} status={segment.status} onAdd={transactionDisabled?undefined:add} onCheckout={openCheckout} disabled={transactionDisabled} onRefundConfirm={()=>{setView("orders");void refresh();}}/>}/></div>
 {view!=="assistant"&&<StorePage>{view==="catalog"?<Catalog key={revision} revision={revision} onAdd={transactionDisabled?undefined:add}/>:view==="orders"?<Orders orders={orders} actions={actions} error={readError} disabled={busy||reading||readError!==null} onRefresh={()=>void refresh()} onPrepare={(order,amount)=>perform(()=>buyerApi.write("/actions/prepare",{orderId:order.orderId,amountMinor:amount,currency:order.product.currency}))} onConfirm={id=>perform(()=>buyerApi.post(`/actions/${encodeURIComponent(id)}/confirm`,{}))}/>:view==="checkout"?<Checkout key={JSON.stringify(quote)} quote={quote} checkouts={checkouts} disabled={transactionDisabled} onRefresh={()=>void refresh()} onCreate={(body:CheckoutCommand)=>perform(()=>buyerApi.write("/checkouts",{...body}))} onPay={id=>perform(()=>buyerApi.post(`/checkouts/${encodeURIComponent(id)}/pay`,{}))}/>:<Profile profile={profile} disabled={busy||reading} onClearMemory={()=>perform(async()=>{await buyerApi.delete("/memory");turn.reloadMemory("");})}/>}</StorePage>}
 </StoreShell>;
}
export default function BuyerPage(){
 const[subject,setSubject]=useState<string|null>(null);const[sessions,setSessions]=useState<SavedSession[]>([]);const[selected,setSelected]=useState<BuyerSession|null>(null);const[revision,setRevision]=useState(0);const[busy,setBusy]=useState(false);const[turnBusy,setTurnBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const logout=useCallback(()=>{buyerApi.setToken(null);setSubject(null);setSelected(null);setSessions([]);setError(null);},[]);
 useEffect(()=>{buyerApi.onUnauthorized=logout;return()=>{buyerApi.onUnauthorized=null;buyerApi.stopChat();buyerApi.setToken(null);};},[logout]);
 async function loadSessions(){const data=await buyerApi.get<{sessions:SavedSession[]}>("/sessions");setSessions(data.sessions);return data.sessions;}
 async function loadSession(id:string){const previous=buyerApi.session;buyerApi.session=id;try{const data=await buyerApi.get<BuyerSession>("/session");setSelected(data);setRevision(n=>n+1);}catch(error){buyerApi.session=previous;throw error;}}
 async function create(){const data=await buyerApi.post<{session_id:string}>("/session");await loadSessions();await loadSession(data.session_id);}
 async function login(loginIdentifier:string,password:string){const data=await buyerApi.post<LoginResult>("/login",{loginIdentifier,password});buyerApi.setToken(data.accessToken);setSubject(data.subject);try{const list=await loadSessions();if(list.length)await loadSession(list[0].session_id);else await create();}catch(error){setError(error instanceof Error?error.message:UNREACHABLE);}}
 async function action(fn:()=>Promise<void>,allowRunningRefresh=false){if(busy||(turnBusy&&!allowRunningRefresh))return;setBusy(true);setError(null);try{await fn();}catch(error){setError(error instanceof Error?error.message:UNREACHABLE);}finally{setBusy(false);}}
 if(!subject)return <Login onLogin={login}/>;
 if(!selected)return <main className="mx-auto max-w-xl space-y-4 p-8"><h1 className="text-xl font-semibold">{error?"会话暂时无法恢复":"正在打开买家工作台"}</h1>{error&&<><p role="alert" className="text-(--danger)">{error}</p><Button disabled={busy} onClick={()=>void action(async()=>{const list=await loadSessions();if(list.length)await loadSession(list[0].session_id);else await create();})}>重试恢复</Button><Button disabled={busy} variant="secondary" onClick={()=>void action(create)}>新建会话</Button><Button disabled={busy} variant="secondary" onClick={logout}>退出</Button></>}</main>;
 return <><BuyerWorkbench key={`${selected.session_id}-${revision}`} subject={subject} selected={selected} sessions={sessions} sessionBusy={busy} onBusy={setTurnBusy} onSelect={id=>void action(()=>loadSession(id))} onCreate={()=>void action(create)} onReload={()=>void action(async()=>{await loadSessions();await loadSession(selected.session_id);},true)} onLogout={logout}/>{error&&<p role="alert" className="fixed bottom-3 left-3 z-50 rounded-xl bg-(--danger-soft) p-3 text-(--danger)">{error}</p>}</>;
}
