// Copyright 2026 Anthropic PBC
// SPDX-License-Identifier: Apache-2.0
"use client";
import { BagPanel,Button,optionValuesLabel } from "web-shared";
import type { JavaCart } from "@/lib/buyer-types";
import { minorMoney } from "@/lib/buyer-checkout";
export default function CartPanel({cart,error,disabled,onSet,onRemove,onCheckout,onRefresh}:{cart:JavaCart|null;error?:string|null;disabled:boolean;onSet:(id:string,quantity:number,version:number)=>void;onRemove:(id:string,version:number)=>void;onCheckout:()=>void;onRefresh:()=>void}) {
 const count=cart?.items.reduce((sum,item)=>sum+item.quantity,0)??0;
 return <BagPanel title="购物车" count={`${count} 件`} isEmpty={cart?.items.length===0} empty="购物车为空。浏览商品或让助手推荐。" footer={<div className="space-y-3"><p className="flex justify-between font-semibold"><span>商品小计</span><span>{cart?minorMoney(cart.subtotalMinor,cart.currency):"待读取"}</span></p><Button disabled={disabled||!cart?.checkoutReady} onClick={onCheckout}>核对并确认结账</Button><p className="text-xs text-(--ink-soft)">配送咨询与商品付款分开。结账前再次核对价格和版本。</p><Button variant="secondary" size="sm" disabled={disabled} onClick={onRefresh}>刷新购物车</Button></div>}>{error?<p role="alert" className="text-sm text-(--danger)">{error}</p>:cart===null?<p role="status">读取购物车…</p>:<ul className="divide-y divide-(--line)">{cart.items.map(item=><li key={item.productId} className="space-y-2 py-3"><div className="flex justify-between gap-2"><strong className="text-sm">{item.name}</strong><span>{minorMoney(item.lineTotalMinor,item.currency)}</span></div><p className="text-xs text-(--ink-soft)">{Object.values(item.optionValues).join(" / ")} · {item.productId}</p>{!item.orderable&&<p className="text-xs text-(--danger)">当前不可结账：请核对上架、库存或价格。</p>}<div className="flex items-center gap-2"><button aria-label={`减少${item.name}数量`} disabled={disabled||item.quantity<=1} onClick={()=>onSet(item.productId,item.quantity-1,cart.version)} className="rounded border px-2 disabled:opacity-40">−</button><span>{item.quantity}</span><button aria-label={`增加${item.name}数量`} disabled={disabled||item.quantity>=24} onClick={()=>onSet(item.productId,item.quantity+1,cart.version)} className="rounded border px-2 disabled:opacity-40">+</button><Button size="sm" variant="secondary" disabled={disabled} onClick={()=>onRemove(item.productId,cart.version)}>移除</Button></div></li>)}</ul>}</BagPanel>;
}
