"use client";
import { useState } from "react";
import { Button } from "web-shared";
import type { CheckoutCommand, CheckoutFacts, JavaCart } from "@/lib/buyer-types";
import { checkoutCommand,minorMoney } from "@/lib/buyer-checkout";
import Delivery from "./Delivery";
import OrderFactsCard from "./OrderFactsCard";
export default function Checkout({quote,checkouts,disabled,onCreate,onPay,onRefresh}:{quote:JavaCart|null;checkouts:CheckoutFacts[];disabled:boolean;onCreate:(body:CheckoutCommand)=>Promise<void>;onPay:(id:string)=>Promise<void>;onRefresh:()=>void}) {
 const [ack,setAck]=useState(false); const [error,setError]=useState<string|null>(null);
 return <div className="space-y-5"><h1 className="text-2xl font-semibold">确认与付款</h1><section className="space-y-3 rounded-xl border border-(--line) bg-(--card) p-4"><h2 className="font-semibold">当前商品报价</h2>{quote?<><p className="text-xs text-(--ink-soft)">购物车版本 {quote.version}。确认后锁定这份报价；若价格或库存变动，服务会拒绝并要求重新确认。</p>{quote.items.map(item=><div key={item.productId} className="flex justify-between gap-3 text-sm"><div className="min-w-0"><span>{item.name} × {item.quantity}</span>{Object.keys(item.optionValues).length>0&&<p className="mt-1 text-xs text-(--ink-soft)">{Object.entries(item.optionValues).map(([name,value])=>`${name}: ${value}`).join(" · ")}</p>}<p className="mt-1 break-all text-xs text-(--ink-soft)">SKU {item.productId}</p></div><span className="shrink-0">{minorMoney(item.lineTotalMinor,item.currency)}</span></div>)}<p className="flex justify-between border-t pt-2 font-semibold"><span>商品支付合计</span><span>{minorMoney(quote.subtotalMinor,quote.currency)}</span></p><p className="text-xs text-(--ink-soft)">不含配送估算费用。创建订单和模拟付款是两个独立确认动作。</p><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} disabled={disabled}/><span>我已核对商品、规格、数量和上述金额，确认创建订单。</span></label><Button disabled={disabled||!ack||!quote.checkoutReady} onClick={()=>{setError(null);try{const body=checkoutCommand(quote);setAck(false);void onCreate(body);}catch(e){setError(e instanceof Error?e.message:"无法确认报价");}}}>确认创建订单</Button></>:<p>正在读取当前报价…</p>}<Button variant="secondary" disabled={disabled} onClick={()=>{setAck(false);onRefresh();}}>重新读取报价</Button>{error&&<p role="alert" className="text-(--danger)">{error}</p>}</section><Delivery disabled={disabled||!quote?.items.length}/><h2 className="text-lg font-semibold">已创建的结账记录</h2>{checkouts.length===0?<p className="text-sm text-(--ink-soft)">当前会话尚无结账记录。</p>:checkouts.map(checkout=><section key={checkout.checkoutId} className="space-y-3 rounded-xl border border-(--line) bg-(--well) p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="break-all text-sm font-semibold">{checkout.checkoutId}</h3><strong>{checkout.paymentStatus} · {minorMoney(checkout.totalMinor,checkout.currency)}</strong></div>{checkout.orders.map(order=><OrderFactsCard key={order.orderId} order={order}/>)}{checkout.paymentStatus!=="PAID"&&<Button disabled={disabled} onClick={()=>void onPay(checkout.checkoutId)}>{checkout.paymentStatus==="PARTIALLY_PAID"?"继续原未付款子单的模拟付款":"确认模拟付款"}</Button>}<p className="text-xs text-(--ink-soft)">付款不自动生成发货事实。中断后先刷新，继续付款复用原子单与付款身份。</p></section>)}</div>;
}
