"use client";
import { useState } from "react";
import { Button } from "web-shared";
import type { ActionRecord,OrderFacts } from "@/lib/buyer-types";
import { localDateTime } from "@/lib/retail-format";
import { minorMoney,parseMinorAmount } from "@/lib/buyer-checkout";
import OrderFactsCard from "./OrderFactsCard";
export default function Orders({orders,actions,error,disabled,onPrepare,onConfirm,onRefresh}:{orders:OrderFacts[]|null;actions:ActionRecord[];error:string|null;disabled:boolean;onPrepare:(order:OrderFacts,amount:number)=>Promise<void>;onConfirm:(id:string)=>Promise<void>;onRefresh:()=>void}) {
 const [refund,setRefund]=useState<OrderFacts|null>(null);const[amount,setAmount]=useState("");const[problem,setProblem]=useState<string|null>(null);const[confirm,setConfirm]=useState<string|null>(null);
 return <div className="space-y-4"><div className="flex justify-between"><h1 className="text-2xl font-semibold">本人订单与退款</h1><Button variant="secondary" disabled={disabled} onClick={onRefresh}>刷新</Button></div>{error&&<p role="alert" className="text-(--danger)">{error}</p>}{orders===null?<p>读取订单…</p>:orders.length===0?<p>没有本人订单。</p>:<><p className="text-xs text-(--ink-soft)">最多展示最近 20 个本人订单，历史金额来自下单快照。</p>{orders.map(order=><OrderFactsCard key={order.orderId} order={order} disabled={disabled} onRefund={value=>{setRefund(value);setProblem(null);setAmount(((value.payment!.amountMinor-value.refunds.reservedAmountMinor)/100).toFixed(2));}}/>)}</>}{refund&&<form className="space-y-3 rounded-xl border-2 border-(--accent) p-4" onSubmit={e=>{e.preventDefault();try{const cents=parseMinorAmount(amount);if(cents>refund.payment!.amountMinor-refund.refunds.reservedAmountMinor)throw new Error("超过当前可申请金额。");setProblem(null);void onPrepare(refund,cents);}catch(e){setProblem(e instanceof Error?e.message:"金额不合法");}}}><h2 className="font-semibold">准备退款：{refund.product.name}</h2><p className="text-xs">仅准备申请，随后核对服务端保存的金额并确认。</p><label className="text-sm">申请金额（{refund.product.currency}）<input inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)} className="ml-2 w-32 rounded border px-2 py-1"/></label><div className="flex gap-2"><Button type="submit" disabled={disabled}>准备申请</Button><Button variant="secondary" disabled={disabled} onClick={()=>setRefund(null)}>关闭</Button></div>{problem&&<p className="text-(--danger)">{problem}</p>}</form>}<h2 className="text-lg font-semibold">保存的退款申请</h2>{actions.length===0?<p className="text-sm text-(--ink-soft)">本会话尚无退款申请。</p>:actions.map(({action,receipt})=><section key={action.pendingActionId} className="space-y-2 rounded-xl border border-(--line) bg-(--card) p-4"><p className="break-all text-sm">订单 {action.orderId}</p><p className="font-semibold">{minorMoney(action.amountMinor,action.currency)} · {receipt?.status??action.state}</p><p className="text-xs text-(--ink-soft)">有效期至 {localDateTime(action.expiresAt)}</p>{receipt?<p className="text-sm">已受理 {localDateTime(receipt.committedAt)}；申请成功不等于已到账。</p>:<><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirm===action.pendingActionId} disabled={disabled} onChange={e=>setConfirm(e.target.checked?action.pendingActionId:null)}/>我确认对上述订单申请此金额退款。</label><Button disabled={disabled||confirm!==action.pendingActionId} onClick={()=>{setConfirm(null);void onConfirm(action.pendingActionId);}}>确认提交退款申请</Button></>}</section>)}</div>;
}
