"use client";
import { Button } from "web-shared";
import type { OrderFacts } from "@/lib/buyer-types";
import { minorMoney } from "@/lib/buyer-checkout";
import { localDateTime } from "@/lib/retail-format";
export default function OrderFactsCard({order,onRefund,disabled}:{order:OrderFacts;onRefund?:(order:OrderFacts)=>void;disabled?:boolean}) {
  const delivery=order.fulfillment;
  return <article className="space-y-3 rounded-xl border border-(--line) bg-(--card) p-4"><header className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold">{order.product.name} × {order.product.quantity}</h3><p className="break-all text-xs text-(--ink-soft)">{order.orderId} · {order.orderKind}</p><p className="mt-1 break-all text-xs text-(--ink-soft)">SKU {order.product.productId}</p></div><strong>{minorMoney(order.product.totalPriceMinor,order.product.currency)}</strong></header><div className="grid gap-3 text-sm sm:grid-cols-2"><div><p>订单：{order.status}</p><p>付款：{order.payment?.state ?? "尚无付款记录"}</p><p className="text-xs text-(--ink-soft)">下单 {localDateTime(order.createdAt)}</p>{order.unpaidDeadline&&<p className="text-xs">待付款截止 {localDateTime(order.unpaidDeadline)}</p>}</div><div>{delivery?<><p>履约：{delivery.method} / {delivery.stage}</p>{delivery.estimatedDeliveryAt&&<p>预计送达 {localDateTime(delivery.estimatedDeliveryAt)}</p>}{delivery.shippedAt&&<p>发货 {localDateTime(delivery.shippedAt)}</p>}{delivery.deliveredAt&&<p>已送达 {localDateTime(delivery.deliveredAt)}</p>}{delivery.delayReason&&<p>{delivery.delayReason}</p>}<p className="text-xs text-(--ink-soft)">观察 {localDateTime(delivery.observedAt)} · {delivery.sourceKind}</p></>:<p className="text-(--ink-soft)">暂无履约记录；付款成功不表示已经发货。</p>}</div></div>{order.refunds.byState.length>0&&<div className="border-t border-(--line) pt-2 text-sm"><p>退款预留 {minorMoney(order.refunds.reservedAmountMinor,order.product.currency)}</p>{order.refunds.byState.map(row=><p key={row.state}>{row.state} · {row.count} 笔 · 申请 {minorMoney(row.requestedAmountMinor,order.product.currency)} · 已退 {minorMoney(row.refundedAmountMinor,order.product.currency)}</p>)}<p className="text-xs text-(--ink-soft)">REQUESTED 是退款申请，尚不代表到账。</p></div>}{onRefund&&order.payment?.state==="SUCCEEDED"&&<Button variant="secondary" size="sm" disabled={disabled} onClick={()=>onRefund(order)}>准备退款申请</Button>}</article>;
}
